/*
 * File:           MoleculeHandler.java
 * Date:           1.6.2005  12:34
 *
 * @author  Aleksi Suomalainen
 * @version generated by NetBeans XML module
 */
package fr.emn.easymol.xml;
import org.xml.sax.*;
public interface MoleculeHandler extends ContentHandler {

    /**
     * 
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_atom(final Attributes meta) throws SAXException;

    /**
     * 
     * A data element event handling method.
     * @param data value or null 
     * @param meta attributes
     */
    public void handle_atom(final java.lang.String data, final Attributes meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_atom() throws SAXException;

    /**
     * 
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_bond(final Attributes meta) throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_molecule(final Attributes meta) throws SAXException;

    /**
     * 
     * A data element event handling method.
     * @param data value or null 
     * @param meta attributes
     */
    public void handle_molecule(final java.lang.String data, final Attributes meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_molecule() throws SAXException;

    /**
     * 
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_compound(final Attributes meta) throws SAXException;

    /**
     * 
     * A container element end event handling method.
     */
    public void end_compound() throws SAXException;
}
