/*
 * File:           MoleculeHandlerImpl.java
 * Date:           1.6.2005  12:34
 *
 * @author  Aleksi Suomalainen
 * @version generated by NetBeans XML module
 */
package fr.emn.easymol.xml;
import org.xml.sax.*;
public class MoleculeHandlerImpl implements MoleculeHandler {

    public static final boolean DEBUG = false;

    public void start_atom(final Attributes meta) throws SAXException {

        if (DEBUG) System.err.println("start_atom: " + meta);
    }

    public void handle_atom(final java.lang.String data, final Attributes meta) throws SAXException {

        if (DEBUG) System.err.println("handle_atom: " + data);
    }

    public void end_atom() throws SAXException {

        if (DEBUG) System.err.println("end_atom()");
    }

    public void handle_bond(final Attributes meta) throws SAXException {

        if (DEBUG) System.err.println("handle_bond: " + meta);
    }

    public void start_molecule(final Attributes meta) throws SAXException {

        if (DEBUG) System.err.println("start_molecule: " + meta);
    }

    public void handle_molecule(final java.lang.String data, final Attributes meta) throws SAXException {

        if (DEBUG) System.err.println("handle_molecule: " + data);
    }

    public void end_molecule() throws SAXException {

        if (DEBUG) System.err.println("end_molecule()");
    }

    public void start_compound(final Attributes meta) throws SAXException {

        if (DEBUG) System.err.println("start_compound: " + meta);
    }

    public void end_compound() throws SAXException {

        if (DEBUG) System.err.println("end_compound()");
    }

    public void characters(char[] values, int param, int param2) throws SAXException {
    }

    public void endDocument() throws SAXException {
    }

    public void endElement(String str, String str1, String str2) throws SAXException {
    }

    public void endPrefixMapping(String str) throws SAXException {
    }

    public void ignorableWhitespace(char[] values, int param, int param2) throws SAXException {
    }

    public void processingInstruction(String str, String str1) throws SAXException {
    }

    public void setDocumentLocator(Locator locator) {
    }

    public void skippedEntity(String str) throws SAXException {
    }

    public void startDocument() throws SAXException {
    }

    public void startElement(String str, String str1, String str2, Attributes attributes) throws SAXException {
    }

    public void startPrefixMapping(String str, String str1) throws SAXException {
    }
}
